server:
  port: 80
  

#自定义配置mq相关参数信息
exchange:
  directExchange:
    name: directExchange
    durable: true
    autoDelete: false
    routingKey: direct_queue_routingKey
#  fanoutExchange: 
#    name: fanoutExchange
#    durable: true
#    autoDelete: false
#  topicExchange: 
#    name: topicExchange
#    durable: true
#    autoDelete: false
  #headersExchangeName: headersExchange
  
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: xiangjiao
    password: bunana
    virtual-host: /xiangjiao
    publisher-confirms: true   #开启发送确认
    publisher-returns: true  #开启发送失败回退
    
    #开启ack
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual #采取手动应答
        #concurrency: 1 # 指定最小的消费者数量
        #max-concurrency: 1 #指定最大的消费者数量
        retry:
          enabled: true # 是否支持重试
  
